"""0.3.1 - reconstruct

Revision ID: d25805b504bf
Revises: 
Create Date: 2022-11-18 21:39:49.280728

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.


revision = 'd25805b504bf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    user_state = postgresql.ENUM('dolnośląskie', 'kujawsko_pomorskie', 'lubelskie', 'lubuskie', 'łódzkie',
                                 'małopolskie', 'mazowieckie', 'opolskie', 'podkarpackie', 'podlaskie', 'pomorskie',
                                 'śląskie', 'świętokrzyskie', 'warmińsko_mazurskie', 'wielkopolskie',
                                 'zachodniopomorskie', name='user_state')
    user_state.create(op.get_bind())
    breed_dog = postgresql.ENUM('breed_dog_small_1', 'breed_dog_medium_2', 'breed_dog_big_3', 'breed_dog_other_4',
                                name='breed_dog')
    breed_dog.create(op.get_bind())
    breed_cat = postgresql.ENUM('breed_cat_small_1', 'breed_cat_medium_2', 'breed_cat_big_3', 'breed_cat_other_4',
                                name='breed_cat')
    breed_cat.create(op.get_bind())
    sex_info = postgresql.ENUM('male', 'female', name='sex_info')
    sex_info.create(op.get_bind())
    kind_info = postgresql.ENUM('dog', 'cat', name='kind_info')
    kind_info.create(op.get_bind())
    walk_route_type = postgresql.ENUM('straight', 'loop', name='walk_route_type')
    walk_route_type.create(op.get_bind())
    walk_places = postgresql.ENUM('shop', 'vet', 'park', 'restaurant', name='walk_places')
    walk_places.create(op.get_bind())


    op.create_table('breed',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('time_updated', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_breed_id'), 'breed', ['id'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('surname', sa.String(length=50), nullable=False),
    sa.Column('city', sa.String(length=30), nullable=False),
    sa.Column('street', sa.String(length=40), nullable=False),
    sa.Column('post_code', sa.String(length=6), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('phone_number', sa.String(length=15), nullable=False),
    sa.Column('login', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('regulations', sa.Integer(), nullable=False),
    sa.Column('hidden_posts', sa.Integer(), nullable=True),
    sa.Column('coins', sa.Integer(), nullable=False),
    sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('time_updated', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('login'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_table('animal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('height', sa.Float(), nullable=False),
    sa.Column('photo', sa.String(length=50), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('pins', sa.Integer(), nullable=True),
    sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('time_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('breed_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['breed_id'], ['breed.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_animal_id'), 'animal', ['id'], unique=False)
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('likes', sa.Integer(), nullable=False),
    sa.Column('reports', sa.Integer(), nullable=True),
    sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('time_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_post_id'), 'post', ['id'], unique=False)
    op.create_table('walk',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('time', sa.Time(), nullable=False),
    sa.Column('distance', sa.Float(), nullable=True),
    sa.Column('coins_gained', sa.Integer(), nullable=False),
    sa.Column('time_limit', sa.Time(), nullable=True),
    sa.Column('route_match', sa.Boolean(), nullable=True),
    sa.Column('start_point_latitude', sa.Float(), nullable=True),
    sa.Column('start_point_longtitude', sa.Float(), nullable=True),
    sa.Column('end_point_latitude', sa.Float(), nullable=True),
    sa.Column('end_point_longtiude', sa.Float(), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_walk_id'), 'walk', ['id'], unique=False)
    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(length=256), nullable=False),
    sa.Column('likes', sa.Integer(), nullable=False),
    sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('time_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comment_id'), 'comment', ['id'], unique=False)
    op.create_table('pin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longtitude', sa.Float(), nullable=False),
    sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('time_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('animal_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['animal_id'], ['animal.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pin_id'), 'pin', ['id'], unique=False)

    op.add_column('user',
                  sa.Column('state', sa.Enum('dolnośląskie', 'kujawsko_pomorskie', 'lubelskie', 'lubuskie', 'łódzkie',
                                             'małopolskie', 'mazowieckie', 'opolskie', 'podkarpackie', 'podlaskie',
                                             'pomorskie', 'śląskie', 'świętokrzyskie', 'warmińsko_mazurskie',
                                             'wielkopolskie', 'zachodniopomorskie',
                                             name='user_state'), nullable=False))
    op.add_column(
        "breed",
        sa.Column('dog_breed',
                  sa.Enum('breed_dog_small_1', 'breed_dog_medium_2', 'breed_dog_big_3', 'breed_dog_other_4',
                          name='breed_dog'), nullable=True),
    )
    op.add_column(
        "breed",
        sa.Column('cat_breed',
                  sa.Enum('breed_cat_small_1', 'breed_cat_medium_2', 'breed_cat_big_3', 'breed_cat_other_4',
                          name='breed_cat'), nullable=True),
    )
    op.add_column(
        "user",
        sa.Column('sex', sa.Enum('male', 'female', name='sex_info'), nullable=True),
    )
    op.add_column(
        "animal",
        sa.Column('sex', sa.Enum('male', 'female', name='sex_info'), nullable=True),
    )
    op.add_column(
        "animal",
        sa.Column('kind', sa.Enum('dog', 'cat', name='kind_info'), nullable=True),
    )
    op.add_column(
        "walk",
        sa.Column('places', sa.Enum('shop', 'vet', 'park', 'restaurant', name='walk_places'), nullable=True),
    )
    op.add_column(
        "walk",
        sa.Column('route_type', sa.Enum('straight', 'loop', name='walk_route_type'), nullable=True),
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pin_id'), table_name='pin')
    op.drop_table('pin')
    op.drop_index(op.f('ix_comment_id'), table_name='comment')
    op.drop_table('comment')
    op.drop_index(op.f('ix_walk_id'), table_name='walk')
    op.drop_table('walk')
    op.drop_index(op.f('ix_post_id'), table_name='post')
    op.drop_table('post')
    op.drop_index(op.f('ix_animal_id'), table_name='animal')
    op.drop_table('animal')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_breed_id'), table_name='breed')
    op.drop_table('breed')
    # ### end Alembic commands ###
