STATIC_BREEDS = ["Chart afgański",
                 "Chart perski - saluki",
                 "Chart rosyjski borzoj",
                 "Chart szkocki",
                 "Wilczarz irlandzki",
                 "Chart afrykański - azawakh",
                 "Chart arabski - sloughi",
                 "Chart hiszpański",
                 "Chart polski",
                 "Chart węgierski",
                 "Charcik włoski",
                 "Greyhound",
                 "Whippet",
                 "Bichon frise",
                 "Bolończyk",
                 "Hawańczyk",
                 "Maltańczyk",
                 "Coton de tuléar",
                 "Lwi piesek",
                 "Pudel duży",
                 "Pudel miniaturowy",
                 "Pudel średni",
                 "Pudel toy",
                 "Gryfonik belgijski",
                 "Gryfonik brukselski",
                 "Brabantczyk",
                 "Chiński Grzywacz",
                 "Lhasa apso",
                 "Shih tzu",
                 "Spaniel tybetański",
                 "Terier tybetański",
                 "Chihuahua",
                 "Cavalier king charles spaniel",
                 "King charles spaniel",
                 "Chin japoński",
                 "Pekińczyk",
                 "Rosyjski toy",
                 "Spaniel kontynentalny miniaturowy",
                 "Kromfohrländer", "Boston terrier",
                 "Buldog francuski",
                 "Mops",
                 "Amerykański spaniel dowodny",
                 "Barbet",
                 "Fryzyjski pies dowodny",
                 "Hiszpański pies dowodny",
                 "Irlandzki spaniel dowodny",
                 "Lagotto romagnolo",
                 "Portugalski pies dowodny",
                 "Clumber spaniel",
                 "Cocker spaniel amerykański",
                 "Cocker spaniel angielski",
                 "Field spaniel",
                 "Kooikerhondje",
                 "Płochacz niemiecki",
                 "Springer spaniel angielski",
                 "Springer spaniel walijski",
                 "Sussex spaniel",
                 "Chesapeake bay retriever",
                 "Curly coated retriever",
                 "Flat coated retriever",
                 "Golden retriever",
                 "Labrador retriever",
                 "Nova scotia duck tolling retriever",
                 "Seter angielski",
                 "Seter irlandzki",
                 "Seter irlandzki czerwono-biały",
                 "Seter szkocki (gordon)",
                 "Pointer",
                 "Gryfon korthalsa",
                 "Wyżeł czeski szorstkowłosy - fousek",
                 "Wyżeł włoski szorstkowłosy",
                 "Duży münsterländer",
                 "Drentse Patrijshond",
                 "Epagneul bleu de picardie",
                 "Epagneul de pond-audemer",
                 "Mały münsterländer",
                 "Spaniel bretoński",
                 "Spaniel francuski",
                 "Spaniel pikardyjski",
                 "Wyżeł fryzyjski", "Wyżeł niemiecki długowłosy",
                 "Braque d’auvergne",
                 "Braque de l’ariege",
                 "Braque du bourbonnais",
                 "Braque saint-germain",
                 "Pudelpointer",
                 "Wyżeł duński",
                 "Wyżeł gaskoński",
                 "Wyżeł hiszpański",
                 "Wyżeł weimarski krótkowłosy",
                 "Wyżeł weimarski długowłosy",
                 "Wyżeł holenderski",
                 "Wyżeł niemiecki krótkowłosy",
                 "Wyżeł niemiecki średni",
                 "Wyżeł austriacki",
                 "Wyżeł bawarski",
                 "Wyżeł bernardyn",
                 "Wyżeł bernenski",
                 "Wyżeł szwajcarski",
                 "Wyżeł entlebucher",
                 "Wyżeł appenzell",
                 "Wyżeł szwajcarski jura",
                 "Wyżeł szwajcarski krótkowłosy",
                 "Wyżeł szwajcarski długowłosy",
                 "Wyżeł szwajcarski szorstkowłosy",
                 "Wyżeł alpejski",
                 "Wyżeł alpejski długowłosy",
                 "Alaskan Malamute",
                 "American Eskimo Dog",
                 "American Foxhound",
                 "American Pit Bull Terrier",
                 "American Water Spaniel",
                 "Anatolian Shepherd Dog",
                 "Australian Cattle Dog",
                 "Australian Shepherd",
                 "Australian Terrier",
                 "Basenji",
                 "Basset Hound",
                 "Beagle",
                 "Bearded Collie",
                 "Beauceron",
                 "Bedlington Terrier",
                 "Belgian Malinois",
                 "Belgian Sheepdog",
                 "Belgian Tervuren",
                 "Bernese Mountain Dog",
                 "Bichon Frise",
                 "Black and Tan Coonhound",
                 "Black Russian Terrier",
                 "Bloodhound",
                 "Bluetick Coonhound",
                 "Boerboel",
                 "Border Collie",
                 "Border Terrier",
                 "Borzoi",
                 "Boston Terrier",
                 "Bouvier des Flandres",
                 "Boxer",
                 "Boykin Spaniel",
                 "Briard",
                 "Brittany",
                 "Brussels Griffon",
                 "Bull Terrier",
                 "Bulldog",
                 "Bullmastiff",
                 "Cairn Terrier",
                 "Canaan Dog",
                 "Cane Corso",
                 "Cardigan Welsh Corgi",
                 "Cavalier King Charles Spaniel",
                 "Cesky Terrier",
                 "Chesapeake Bay Retriever",
                 "Chihuahua",
                 "Chinese Crested Dog",
                 "Chinese Shar-Pei",
                 "Chow Chow",
                 "Clumber Spaniel",
                 "Cocker Spaniel",
                 "Collie",
                 "Coonhound",
                 "Coton de Tulear",
                 "Curly-Coated Retriever",
                 "Dachshund",
                 "Dalmatian",
                 "Dandie Dinmont Terrier",
                 "Doberman Pinscher",
                 "Dogue de Bordeaux",
                 "English Cocker Spaniel",
                 "English Foxhound",
                 "English Setter",
                 "English Springer Spaniel",
                 "English Toy Spaniel",
                 "Entlebucher Mountain Dog",
                 "Eskimo Dog",
                 "Feist",
                 "Field Spaniel",
                 "Finnish Lapphund",
                 "Finnish Spitz",
                 "Flat-Coated Retriever",
                 "Fox Terrier",
                 "Foxhound",
                 "French Bulldog",
                 "Galgo Spanish Greyhound",
                 "German Pinscher",
                 "German Shepherd",
                 "German Shorthaired Pointer",
                 "German Wirehaired Pointer",
                 "Giant Schnauzer",
                 "Glen of Imaal Terrier",
                 "Golden Retriever",
                 "Gordon Setter",
                 "Great Dane",
                 "Great Pyrenees",
                 "Greater Swiss Mountain Dog",
                 "Greyhound",
                 "Hamiltonstovare",
                 "Harrier",
                 "Havanese",
                 "Hound",
                 "Hovawart",
                 "Ibizan Hound",
                 "Icelandic Sheepdog",
                 "Irish Red and White Setter",
                 "Irish Setter",
                 "Irish Terrier",
                 "Irish Water Spaniel",
                 "Irish Wolfhound", "Italian Greyhound",
                 "Japanese Chin",
                 "Japanese Spitz",
                 "Keeshond",
                 "Kerry Blue Terrier",
                 "Komondor",
                 "Kuvasz",
                 "Labrador Retriever",
                 "Lakeland Terrier",
                 "Lancashire Heeler",
                 "Leonberger",
                 "Lhasa Apso",
                 "Lowchen",
                 "Maltese",
                 "Manchester Terrier",
                 "Mastiff",
                 "Miniature Australian Shepherd",
                 "Miniature Bull Terrier",
                 "Miniature Pinscher",
                 "Miniature Schnauzer",
                 "Mountain Cur",
                 "Mountain Dog",
                 "Neapolitan Mastiff",
                 "Newfoundland",
                 "Norfolk Terrier",
                 "Norwegian Buhund",
                 "Norwegian Elkhound",
                 "Norwegian Lundehund",
                 "Norwich Terrier",
                 "Old English Sheepdog",
                 "Old Time Farm Shepherd",
                 "Otterhound",
                 "Papillon",
                 "Pekingese",
                 "Pembroke Welsh Corgi",
                 "Pharaoh Hound",
                 "Pointer",
                 "Polish Lowland Sheepdog",
                 "Pomeranian",
                 "Poodle",
                 "Portuguese Water Dog",
                 "Presa Canario",
                 "Pug",
                 "Puli",
                 "Pyrenean Mountain Dog",
                 "Rat Terrier",
                 "Redbone Coonhound",
                 "Rhodesian Ridgeback",
                 "Rottweiler",
                 "Saint Bernard",
                 "Saluki",
                 "Samoyed",
                 "Schipperke",
                 "Scottish Deerhound",
                 "Scottish Terrier",
                 "Sealyham Terrier",
                 "Shetland Sheepdog",
                 "Shih Tzu",
                 "Siberian Husky",
                 "Silky Terrier",
                 "Skye Terrier",
                 "Sloughi",
                 "Smooth Fox Terrier",
                 "Soft Coated Wheaten Terrier",
                 "Spanish Water Dog",
                 "Spinone Italiano",
                 "Staffordshire Bull Terrier",
                 "Standard Schnauzer",
                 "Sussex Spaniel",
                 "Swedish Vallhund",
                 "Tibetan Mastiff",
                 "Tibetan Spaniel",
                 "Tibetan Terrier",
                 "Toy Fox Terrier",
                 "Treeing Tennessee Brindle",
                 "Treeing Walker Coonhound",
                 "Vizsla",
                 "Weimaraner",
                 "Welsh Springer Spaniel",
                 "Welsh Terrier",
                 "West Highland White Terrier",
                 "Whippet",
                 "Wire Fox Terrier",
                 "Wirehaired Pointing Griffon",
                 "Wirehaired Vizsla",
                 "Xoloitzcuintli",
                 "Yorkshire Terrier"]
